# Generated by Django 4.2.6 on 2023-10-28 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('usuario', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('producto', models.CharField(default='', max_length=255, unique=True)),
                ('cantidad', models.SmallIntegerField(default=1)),
                ('estado_compra', models.CharField(default='inmediata', max_length=255)),
            ],
            options={
                'db_table': 'carrito',
                'db_table_comment': 'Tabla para el carrito de compras',
                'managed': False,
            },
        ),
    ]
